[tools]
actionlint = "latest"
bazelisk = "latest"
bun = "1"
fd = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
hadolint = "latest"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
node = "24"
pnpm = "10"
ripgrep = "latest"
usage = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
